<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>uw_localization</name>
  <version>0.2.0</version>
  <description>OpenVINS state estimation and optional independent ORB-SLAM3 stereo mapping</description>
  <maintainer email="ChoujiajunStats@126.com">Jiajun Zhou</maintainer>
  <license>GPL-3.0-or-later</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>python3-yaml</exec_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>rosgraph_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_msgs</depend>
  <depend>eigen</depend>
  <depend>opencv</depend>
  <exec_depend>uw_perception</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>