<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>uw_ui</name>
  <version>0.1.0</version>
  <description>Read-only RViz layouts and run-scoped visualization windows</description>
  <maintainer email="ChoujiajunStats@126.com">Jiajun Zhou</maintainer>
  <license>LicenseRef-Not-Yet-Licensed</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>libx11-6</exec_depend>
  <exec_depend>libxtst6</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>